#! /bin/bash

 #Your task is to write and test a function which takes
#three arguments (a year, a month, and a day of the
#month) and returns the corresponding day of the year, or
#returns None if any of the arguments is invalid.
#Input: (2000, 12, 31) - (Y, M, D)
#Result:366
#Input: (2000, 1, 1) - (Y, M, D)
#Result:1
#Input: (1900, 3, 1) - (Y, M, D)
#Result:60
#Input: (2000, 3, 1) - (Y, M, D)
#Result:61




#three arg that are out of function : year, month, day
function test () {
day=$1
month=$2
year=$3


if [[ $date -d "     " +%j ]]
then
echo 
else
then
echo "None"

}
